### ISSUE TITLE
TypeError: "secret" does not match any of the allowed types

### ISSUE THREAD

**Issue by arnonrdp** [TheBoringDude/nextjs-fauna-auth0#4]
Hi, I just used you project as a template, followed step-by-step and after running `yarn dev` it displays the main page as it should.

But when I click login it returns `Internal Server Error` and console.log shows it:

```console
TypeError: "secret" does not match any of the allowed types
    at Object.get (/Users/arnon/Sites/GitHub/virtual-bookshelf/node_modules/@auth0/nextjs-auth0/dist/auth0-session/get-config.js:145:15)
    at Object.getConfig (/Users/arnon/Sites/GitHub/virtual-bookshelf/node_modules/@auth0/nextjs-auth0/dist/config.js:65:40)
    at Object.initAuth0 (/Users/arnon/Sites/GitHub/virtual-bookshelf/node_modules/@auth0/nextjs-auth0/dist/index.js:22:49)
    at getInstance (/Users/arnon/Sites/GitHub/virtual-bookshelf/node_modules/@auth0/nextjs-auth0/dist/index.js:18:24)
    at handleAuth (/Users/arnon/Sites/GitHub/virtual-bookshelf/node_modules/@auth0/nextjs-auth0/dist/index.js:69:33)
    at eval (webpack-internal:///./src/pages/api/auth/[...auth0].ts:25:127)
    at Object../src/pages/api/auth/[...auth0].ts (/Users/arnon/Sites/GitHub/virtual-bookshelf/.next/server/pages/api/auth/[...auth0].js:44:1)
    at __webpack_require__ (/Users/arnon/Sites/GitHub/virtual-bookshelf/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/Users/arnon/Sites/GitHub/virtual-bookshelf/.next/server/pages/api/auth/[...auth0].js:76:52)
    at /Users/arnon/Sites/GitHub/virtual-bookshelf/.next/server/pages/api/auth/[...auth0].js:77:28
```

Here is what I did:
- I renamed the file `.env.local.template` to `.env.local`;
- On fauna.com I created a new DB, went to security and generate a new Secret Key;
- I inserted this secret key in `.env.local` right on `FAUNADB_SECRET_KEY`;
- I inserted the name of the database in line 3 of `newuser.js`.

After running `yarn setup:db` it created the users collection and `user_by_id` index.
I really don't know what I missed. Do you know what it could be?

**Comment by TheBoringDude** [comment]
> Hi, I just used you project as a template, followed step-by-step and after running `yarn dev` it displays the main page as it should.
> 
> But when I click login it returns `Internal Server Error` and console.log shows it:
> 
> ```
> TypeError: "secret" does not match any of the allowed types
>     at Object.get (/Users/arnon/Sites/GitHub/virtual-bookshelf/node_modules/@auth0/nextjs-auth0/dist/auth0-session/get-config.js:145:15)
>     at Object.getConfig (/Users/arnon/Sites/GitHub/virtual-bookshelf/node_modules/@auth0/nextjs-auth0/dist/config.js:65:40)
>     at Object.initAuth0 (/Users/arnon/Sites/GitHub/virtual-bookshelf/node_modules/@auth0/nextjs-auth0/dist/index.js:22:49)
>     at getInstance (/Users/arnon/Sites/GitHub/virtual-bookshelf/node_modules/@auth0/nextjs-auth0/dist/index.js:18:24)
>     at handleAuth (/Users/arnon/Sites/GitHub/virtual-bookshelf/node_modules/@auth0/nextjs-auth0/dist/index.js:69:33)
>     at eval (webpack-internal:///./src/pages/api/auth/[...auth0].ts:25:127)
>     at Object../src/pages/api/auth/[...auth0].ts (/Users/arnon/Sites/GitHub/virtual-bookshelf/.next/server/pages/api/auth/[...auth0].js:44:1)
>     at __webpack_require__ (/Users/arnon/Sites/GitHub/virtual-bookshelf/.next/server/webpack-runtime.js:33:42)
>     at __webpack_exec__ (/Users/arnon/Sites/GitHub/virtual-bookshelf/.next/server/pages/api/auth/[...auth0].js:76:52)
>     at /Users/arnon/Sites/GitHub/virtual-bookshelf/.next/server/pages/api/auth/[...auth0].js:77:28
> ```
> 
> Here is what I did:
> 
>     * I renamed the file `.env.local.template` to `.env.local`;
> 
>     * On fauna.com I created a new DB, went to security and generate a new Secret Key;
> 
>     * I inserted this secret key in `.env.local` right on `FAUNADB_SECRET_KEY`;
> 
>     * I inserted the name of the database in line 3 of `newuser.js`.
> 
> 
> After running `yarn setup:db` it created the users collection and `user_by_id` index.
> I really don't know what I missed. Do you know what it could be?

Did you fill everything in your `.env.local`?
The error is caused by missing value of `AUTH0_SECRET` in the `.env.local`, you should generate a random secret key or code for the application to use.

**Comment by arnonrdp** [comment]
I got it! It works but how do I fill these:

```env
AUTH0_BASE_URL=
AUTH0_ISSUER_BASE_URL=
AUTH0_CLIENT_ID=
AUTH0_CLIENT_SECRET=
```

Do I have to deploy first?

**Comment by TheBoringDude** [comment]
You have to create an Auth0 app for this one.

This guide will help you: https://auth0.com/docs/quickstart/webapp/nextjs/01-login

Sorry, I did not include a tutorial for this one.

**Comment by TheBoringDude** [comment]
Routes are already configured, but you can check them and modify them at your needs.

**Comment by arnonrdp** [comment]
I really appreciate!

Everything worked after this complementing guide.

By the way, thanks for sharing this template.
